### PR TITLE
Use oldest-supported-numpy

### PR DESCRIPTION
**Pull request by enzbus**
For https://github.com/bodono/scs-python/issues/77; @phschiele @SteveDiamond you can try the CI on this PR, hopefully it works.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
It didn't work with oldest-supported-numpy, so trying again with the explicit NumPy versions.

**Comment by enzbus** [comment]
Ok, looks good. It fixed the issue on 3.8. It fails on Windows because we're building from source (you may also add `openblas` to the conda installs, for fun), when installing from pip/pypi it doesn't matter. Then some other failures seem to be due to `scip`.

**Comment by enzbus** [comment]
You can rerun with the `oldest-supported-numpy` to see if there are different failures?

**Comment by SteveDiamond** [comment]
In the interest of getting things working I dropped the pyscipopt installation on linux and mac.

**Comment by enzbus** [comment]
I got the needed fixes from both PRs, if this passes all tests I think you can merge. Also consider the CLA signed. Thanks!

**Comment by SteveDiamond** [comment]
There are some other changes needed. The main PR now is https://github.com/cvxpy/cvxpy/pull/2292

**Comment by SteveDiamond** [comment]
Addressed in #2292

**Comment by enzbus** [comment]
OK @SteveDiamond @phschiele but you can still replace all the `numpy` clauses in the build section of your `pyproject.toml` with `oldest-supported-numpy`. As you see it passes all tests. It is the official solution by the Numpy team for that job, makes things cleaner and more maintenable for you. Sorry but I have to act whenever I see unnecessary complications in dependencies, especially in their package management code. Thanks!

**Review by SteveDiamond — APPROVED** [review]

**Pull request merged**
