### PR TITLE
Fix tests that started failing with Mosek 10

### PR DESCRIPTION
**Pull request by SteveDiamond**
## Description
Fixes tests that started failing once Mosek 10 was deployed.
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by phschiele — COMMENTED** [review]
LGTM!

**Comment by rileyjmurray** [comment]
@SteveDiamond one thing stands out to me. This power cone test has the same optimal solution as this SOCP test:
https://github.com/cvxpy/cvxpy/blob/83b684ccae0c4f514eacb2ffd6f4d9b7af597ba9/cvxpy/tests/solver_test_helpers.py#L268-L295
So actually changing the expected optimal values doesn't seem appropriate.

**Comment by SteveDiamond** [comment]
I wasn't aware of that. If I keep the old optimal values, I need to do
```
    def test_mosek_pcp_1(self) -> None:
        StandardTestPCPs.test_pcp_1(solver='MOSEK', places=2)
```
That might be better, not sure.

**Comment by rileyjmurray** [comment]
Hmm. As an initial step how about we use MOSEK to solve ``socp_1`` and ``pcp_1`` with verbose=True, and see how the outputs differ. I think that the optimal solution is unique since there's a binding 2-norm constraint. But if both solver logs look good then we can try visualizing the feasible set; it might be that there's a neighborhood of very-close-to-optimal solutions for this problem. If that's the case then it might make sense to change the problem data to avoid that.

Ping @aszekMosek, in case you have thoughts.

**Pull request merged**
