### PR TITLE
Fix bug with calling Mosek simplex solver

### PR DESCRIPTION
**Pull request by SteveDiamond**
## Description
The Mosek simplex and dual simplex solver cannot be used right now due to a simple interface bug, fixed here. I also made the Clarabel interface a bit more robust because it was failing on my old Clarabel version.

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by rileyjmurray** [comment]
@SteveDiamond, if you want to backport this to 1.1 and 1.2 then you'd need to move the Clarabel changes into a separate PR.

**Comment by SteveDiamond** [comment]
> @SteveDiamond, if you want to backport this to 1.1 and 1.2 then you'd need to move the Clarabel changes into a separate PR.

Good point, I will remove the Clarabel changes here.

**Comment by SteveDiamond** [comment]
@Paulnkk for some reason the accept unknown test is failing on windows now...

**Comment by Paulnkk** [comment]
@SteveDiamond, sorry for the late response I am currently visiting my graduation, will catch up with the error and try to fix it

**Comment by SteveDiamond** [comment]
> @SteveDiamond, sorry for the late response I am currently visiting my graduation, will catch up with the error and try to fix it

That's ok, it is being worked on here: #2127

**Review by PTNobel — APPROVED** [review]
I'm not too familiar with this section of the code so a second review may be wise but lgtm

**Pull request merged**
