### PR TITLE
Add option save_file

### PR DESCRIPTION
**Pull request by wujianjack**
## Description
Add option `save_file` to enable writing out problem loaded into COPT to file.

## Type of change
- [x] New feature (backwards compatible)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by phschiele — COMMENTED** [review]
@wujianjack Changes look good. You might consider adding a test similar to 
https://github.com/cvxpy/cvxpy/blob/114d7c1af3a7ff6e74990b303663f71baf35068b/cvxpy/tests/test_gurobi_write.py#L26-L49

If you do so, please don't manually create the directory like in the link, but use the pytest tempdir fixture: https://docs.pytest.org/en/6.2.x/tmpdir.html#the-tmpdir-fixture

**Comment by SteveDiamond** [comment]
@wujianjack please wrap up this PR within the next week if you want it included in the 1.5 release. Thanks for your help maintaining the interface!

**Comment by wujianjack** [comment]
> @wujianjack please wrap up this PR within the next week if you want it included in the 1.5 release. Thanks for your help maintaining the interface!

Sorry for the delay, I have updated the fix.

**Review by SteveDiamond — APPROVED** [review]
LGTM

**Pull request merged**
