### PR TITLE
Initial cut at adding error on raw float keys and tuples of floats

### PR DESCRIPTION
**Pull request by PTNobel**
## Description

Per the chat, we decided that `cp.Variable(4)[2.5]` should be an error. This is my first cut at making it one.

I wasn't exactly sure where to put the source of the error or how to structure it. My preference would be to whitelist certain types ala NumPy and validate them that way, but I figured I'd start by banning floats since that occurs the most (in code like `x[5/2]`).

It is worth noting we already have this error for arrays of floats:
```python
ipdb> cp.Variable(5)[2:][np.array([1.5])]
*** IndexError: arrays used as indices must be of integer (or boolean) type

```

Let me know if we should move it and how many unit tests this needs!

## Type of change
- [ ] New feature (backwards compatible)
- [x] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Tests for indexing go in test_expressions.py

**Comment by PTNobel** [comment]
Should be ready to go! I can squash down to one commit if that's preferred.

**Comment by PTNobel** [comment]
Note this PR breaks the following code:

```python
x = cp.Variable(4)
y = x[4 / 2]
```
when they should have written
```python
x = cp.Variable(4)
y = x[4 // 2]
```

**Comment by SteveDiamond** [comment]
> Note this PR breaks the following code:
> 
> ```python
> x = cp.Variable(4)
> y = x[4 / 2]
> ```
> 
> when they should have written
> 
> ```python
> x = cp.Variable(4)
> y = x[4 // 2]
> ```

Is this how numpy behaves?

**Comment by PTNobel** [comment]
NumPy does not except indexing with `4/2`.

**Comment by PTNobel** [comment]
Now all the tests pass? I'm not sure what changed.

Regardless, this should be good to merge! I can squash the commits if you'd like, but I think the default merging for this project involves a squash?

**Review by SteveDiamond — APPROVED** [review]

**Comment by SteveDiamond** [comment]
I reran the benchmark test. LGTM, thanks for fixing this!

**Comment by phschiele** [comment]
@PTNobel I think there was a broader issue with GHA performance. Changes look good to me.

**Pull request merged**
