### PR TITLE
release branch for 1.6.x

### PR DESCRIPTION
**Pull request by Transurgeon**
## Description
Please include a short summary of the change.

### CODE REVIEW

**Comment by Transurgeon** [comment]
let's wait until diffcp is fixed. Issues look like just importing so hopefully its not too bad. Good luck @PTNobel !!

**Comment by PTNobel** [comment]
diffcp should be fixed!

**Comment by Transurgeon** [comment]
somehow its printing this while we are installing diffcp==1.1.2
```
(CVXPY) Nov 10 03:38:17 PM: Encountered unexpected exception importing solver DIFFCP:
ImportError('diffcp >= 1.0.15 is required')
(CVXPY) Nov 10 03:38:17 PM: Encountered unexpected exception importing solver DIFFCP:
ImportError('diffcp >= 1.0.15 is required')
['CBC', 'CLARABEL', 'COPT', 'CVXOPT', 'DAQP', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'GUROBI', 'HIGHS', 'MOSEK', 'OSQP', 'PIQP', 'PROXQP', 'SCIP', 'SCIPY', 'SCS']
```
then the tests all fail because apparently it thinks diffcp is not installed :(

**Comment by Transurgeon** [comment]
closing this as we don't want to merge it to master

**Pull request closed without merging**
