### PR TITLE
Fix old print statements

### PR DESCRIPTION
**Pull request by r-barnes**
Fixes some Python 2 print statements, now that Python2 is gone forever.

But since these issues are still here, maybe these files haven't been used in a _long_ time and should be removed?

### CODE REVIEW

**Comment by r-barnes** [comment]
@SteveDiamond - Tests are passing.

**Comment by akshayka** [comment]
Let's delete these files, you're right @r-barnes, we don't need them. Good catch!

**Comment by r-barnes** [comment]
@akshayka : Should I remove `cvxpy/cvxcore/tests/python/364A_scripts/**` or `cvxpy/cvxcore/tests/python/**`?

**Comment by akshayka** [comment]
Let's delete `cvxpy/cvxcore/tests/python/**`. The code is unused, and incorrect. (cvxcore has changed a lot since these tests were written.)

In the future we could and perhaps should write proper tests for cvxcore.

**Comment by r-barnes** [comment]
@akshayka : I've removed those files along with `cvxpy/cvxcore/tests/.keep` because there was nothing left in the directory `tests/` subdir. Let me know if I should add that back.

**Review by akshayka — APPROVED** [review]

**Pull request merged**
