### PR TITLE
Prep for 1.3.1

### PR DESCRIPTION
**Pull request by SteveDiamond**
## Description
This MR is prep for patch 1.3.1. It includes the following MRs:

#2053 
#2044 
#2043 
#2029 
#2028 
#2022 
#2017 
#2016 
#2008 
#2054
#2063 
#2067
#2058 
#2009
#2060 
#2001

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Unsure whether to include #2054

**Comment by rileyjmurray** [comment]
@SteveDiamond I think that backporting #2054 is fine.

Porting #2009 is a little delicate because I think the updated code might raise a new type of exception that it wasn't raising earlier. @phschiele can say whether or not that's the case. Assuming that the type of exceptions __wouldn't be changed__ by #2009, I think it should be backported.

I'm not in favor of porting #2007. The renaming of those folders is just there to help developers. Moving forward, developers only need to concern themselves with the code that exists on ``master``. So there isn't much value-add in porting #2007. By contrast, porting #2007 might break some peoples' code. (Note: I don't think that would violate semantic versioning by breaking such code. It would be permissible since our declaration of a public API wouldn't be affected. I'm coming at this from a practical perspective of "if it ain't broke, don't fix it.")

**Comment by PTNobel** [comment]
@rileyjmurray re #2007, do you think there will be easier to backport future fixes to ther 1.3 series if we backport the refactor?

**Comment by rileyjmurray** [comment]
@parthb83 hmm ... that's a good question. Hopefully, it wouldn't be too bad. I suggest that we release without #2007 for 1.3.1. If we have trouble preparing 1.3.2 due to missing the changes in #2007, then we can merge #2007 into the 1.3.x branch before any other change needed for 1.3.2. How's that sound?

**Comment by PTNobel** [comment]
SGTM.

**Comment by phschiele** [comment]
@rileyjmurray #2009 reraises the same exception type `ArpackNoConvergence`, only with an extended error message. So it should be fine to backport it.

**Comment by SteveDiamond** [comment]
Ok I think this is done. I don't see any remaining MRs that could go in.

**Review by phschiele — APPROVED** [review]
Looks good, double checked all master merges since the 1.3. release. 
The only question I had was #2001, but I saw you removed the backport label. What was the reason for that?

**Comment by SteveDiamond** [comment]
> Looks good, double checked all master merges since the 1.3. release. The only question I had was #2001, but I saw you removed the backport label. What was the reason for that?

Thanks! I thought #2001 was already integrated, but I checked again and it wasn't. Merged in now.

**Comment by SteveDiamond** [comment]
@h-vetinari we are going to release this as a patch soon.

**Pull request merged**
