### PR TITLE
fixing typo in documentation

### PR DESCRIPTION
**Pull request by Transurgeon**
## Description
I found a small typo in the documentation. 
It is in the "derivative fundamental" sub-section. 
"sensitvity" -> "sensitivity"

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by phschiele — APPROVED** [review]
Nice catch, thanks @Transurgeon!

**Comment by phschiele** [comment]
@Transurgeon The license agreement assistant does not seem to have picked up your acceptance. This is generally not a problem, just click on accept and if you already have, just comment that you did. Thanks a lot!

**Comment by Transurgeon** [comment]
Hello, I have indeed accepted the license agreement :)

image

**Comment by phschiele** [comment]
> also, I saw on the discord that you guys wanted to potentially add support for complex differentiation to cvxpy.
> 
> I was wondering if you had any resources which I could refer to get up to speed on the challenges and what exactly needs to be done?
> 
> This seems like an interesting challenge and a great opportunity to learn a thing or two!

@Transurgeon That's great, I suggest you open an issue for this topic this to discuss it in more detail.

**Pull request merged**
