### PR TITLE
Cherrypick/1.1.x

### PR DESCRIPTION
**Pull request by SteveDiamond**
## Description
Cherry picks the following PRs:

https://github.com/cvxpy/cvxpy/pull/1882

https://github.com/cvxpy/cvxpy/pull/1880

https://github.com/cvxpy/cvxpy/pull/1852

https://github.com/cvxpy/cvxpy/pull/1851

https://github.com/cvxpy/cvxpy/pull/1844

https://github.com/cvxpy/cvxpy/pull/1835

https://github.com/cvxpy/cvxpy/pull/1829

#1855 

#1886 

#1898 

#1922 

#1854 

#1871 

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
The tests fail for Python 3.6 because they use the old mosek version. I think this is fine and we can still merge. 1.3 is coming out soon and 1.1 will no longer be supported at that point.

**Comment by rileyjmurray** [comment]
@SteveDiamond see my comment on your PR that changed the MOSEK test.

**Comment by rileyjmurray** [comment]
@SteveDiamond please add https://github.com/cvxpy/cvxpy/commit/3fad7747e2f624d455ebaec148a2b906b3cb5a6e to this PR when you get a chance.

**Comment by phschiele** [comment]
@SteveDiamond I've looked through the PRs since the last release that were classified as bug fixes, but not yet included in the two cherry-pick PRs: 
#1854
#1859 (only relevant for cherry pick 1.2.x PR)
#1871

**Comment by SteveDiamond** [comment]
> @SteveDiamond I've looked through the PRs since the last release that were classified as bug fixes, but not yet included in the two cherry-pick PRs: #1854 #1859 (only relevant for cherry pick 1.2.x PR) #1871

Great! I've cherry picked these PRs.

**Comment by phschiele** [comment]
@SteveDiamond I think that all bug-fix PRs are incorporated, and everything is passing. Both PRs LGTM.

**Pull request merged**
