### PR TITLE
fix issue in xpress interface for ``prob_.attribute``

### PR DESCRIPTION
**Pull request by Transurgeon**
## Description
Please include a short summary of the change.
Explanation in title. Noticed this in the most recent CI builds.
Related [dcoumentation](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/COLS.html) for the changed attribute.

ADDITIONAL CHANGE: deleting sonarcloud build because it is causing problems. 
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by SteveDiamond — APPROVED** [review]

**Comment by SteveDiamond** [comment]
We could also bump the minimum xpress in pyproject.toml

**Comment by Transurgeon** [comment]
> We could also bump the minimum xpress in pyproject.toml

which version should we put? I am not sure when they introduced this new change (but it must have been relatively recent).

**Comment by SteveDiamond** [comment]
> > We could also bump the minimum xpress in pyproject.toml
> 
> which version should we put? I am not sure when they introduced this new change (but it must have been relatively recent).

idk. let's just merge this fix, too much trouble to figure out.

**Comment by PTNobel** [comment]
Should this be backported?

**Comment by Transurgeon** [comment]
Yea I think so, why not. I will add it to the list.

**Pull request merged**
