### PR TITLE
Fix IsRowMajor assertion

### PR DESCRIPTION
**Pull request by r-barnes**
## Description
Compilation currently fails when assertions are enabled with:
```
cvxpy/cvxcore/src/LinOpOperations.cpp: In function ‘Tensor get_kronl_mat(const LinOp&, int)’:
cvxpy/cvxcore/src/LinOpOperations.cpp:379:25: error: ‘Eigen::SparseMatrixBase<Eigen::SparseMatrix<double> >::IsRowMajor’ cannot be used as a function
  379 |   assert(!rh.IsRowMajor());
      |                         ^
```
Here, we fix this issue by referring to the enum directly. The code now compiles, though I can't test it because master is broken with `AttributeError: module '_cvxcore' has no attribute 'KRON_R'`

Issue link: #1690 

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [X] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [X] Add our license to new files.
- [X] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by rileyjmurray** [comment]
@r-barnes regarding ``KRON_R``, that failure message is odd. Is it possible that Python is finding an old version of ``_cvxcore``? It would help if you could show the workflow you're using to modify cvxcore (including how you run swig and try to install cvxpy).

**Comment by phschiele** [comment]
@r-barnes I tried this on a fresh clone of your fork. Indeed, installing fails with assertions enabled when your fix is not in place.
Regarding your comment `ATTENTION!`. Does that imply that this change should not be merged? I don't know which downsides it would have to keep assertions permanently enabled, but an alternative could be to set the flag `CFLAGS="-UNDEBUG"` while installing on the CI, so every code will be checked with assertions without making changes to `setup.py`.

**Comment by r-barnes** [comment]
@phschiele - I put the attention there because it's possible `NDEBUG` can affect performance. I would _not_ expect this to be the case unless you have `assert` inside of a tight loop or class accessors.

**Comment by phschiele** [comment]
@cvxpy/maintainers Could you please merge the current master into this branch so we get retrigger the CI and get the benchmarks?

**Comment by SteveDiamond** [comment]
> @cvxpy/maintainers Could you please merge the current master into this branch so we get retrigger the CI and get the benchmarks?

Done.

**Comment by phschiele** [comment]
Since we rarely make changes to cvxcore, I have instead added instructions on how to enable debug checks to the README of CVXCORE.

**Review by SteveDiamond — APPROVED** [review]

**Pull request merged**
