### PR TITLE
Added ECOS support in DIFFCP

### PR DESCRIPTION
**Pull request by bstellato**
This PR adds ECOS support within `DIFFCP` calls from CVXPY.  It is done by passing the solver-specific option `solve_method`, for example,

```python
problem.solve(requires_grad=True, solver=cp.DIFFCP, solve_method="ECOS")
```

As expected, it does not support warm-starting, but it can be much more reliable than SCS for some problems.

This  PR depends on https://github.com/cvxgrp/diffcp/pull/42 (the returned ECOS info needs to match SCS format).

I have modified the `test_derivative.py` file to test also ECOS (and excluded the exponential cone examples).

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Looks pretty good. Any idea what's going on with the tests?

**Comment by bstellato** [comment]
Thanks for checking this, @SteveDiamond. The diffcp PR  https://github.com/cvxgrp/diffcp/pull/42 needs to be merged first.

**Comment by SteveDiamond** [comment]
@bstellato could you resolve the merge conflict? Not sure what changes are present here.

**Comment by SteveDiamond** [comment]
@akshayka technically this changes the API right, so we need two reviewers?

**Comment by akshayka** [comment]
Shouldn't some of the tests exercise ECOS? It looks like the tests only use SCS right now.

**Comment by bstellato** [comment]
Guys, I have updated the branch with the latest master. @akshayka, I have disabled some derivative tests with ECOS because some cones are unsupported and I was getting an error. If you check `test_derivative.py`, only some of the tests run just `cp.SCS`.

I believe tests are still failing because `diffcp` [package](https://pypi.org/project/diffcp/) has not been updated after https://github.com/cvxgrp/diffcp/pull/42 was merged.

**Comment by bstellato** [comment]
Thanks @akshayka for making a new diffcp release. It looks like all tests are passing now.

**Comment by akshayka** [comment]
@bstellato, want to rebase this change on top of master? Looks like there are conflicts.

**Comment by bstellato** [comment]
@akshayka if you have time, I have rebased it.

**Review by akshayka — APPROVED** [review]
LGTM! Sorry for the delay.

**Pull request merged**
