### PR TITLE
Allow deecopy of constraints

### PR DESCRIPTION
**Pull request by phschiele**
## Description
Always compare `expression.id` instead of (implicitly) `hash(expression)` for variables and parameters.
Issue link (if applicable): #1827 

TODO:
A question remains if cvxpy should always be two instances to be the same if they have the same `.id`.
E.g. what is the expected behavior of the following (a similar example can be constructed for parameters):

```py
    x = cp.Variable(nonneg=True)
    y = copy.deepcopy(x)

    obj = cp.Minimize((x + y))
    prob = cp.Problem(obj)
    prob.solve()
```
There are also the `.copy()` functions, which do not deepcopy the leaves, presumably for this very reason.
Should `deepcopy(expression)` be generally discouraged? 

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by SteveDiamond — APPROVED** [review]

**Comment by SteveDiamond** [comment]
I would say in your example x and y are the same variable. cvxpy expressions are supposed to be immutable, so I can't see any benefit or purpose of deepcopy over regular copy, but if people want to deepcopy for some reason it should work. So the PR is valuable.

**Comment by phschiele** [comment]
@SteveDiamond Thanks, I agree that there should not be a reason to deepcopy. Just to prevent introducing subtle bugs here, the following problem:
```py
    x = cp.Variable(nonneg=True)
    y = copy.copy(x)

    obj = cp.Minimize((x + y))
    prob = cp.Problem(obj, [y >= 0.75])
    prob.solve()
```
Would result in 
`obj.value = 1.75`, `x.value = 0.75`, `y.value = 0.75` before this PR, but
`obj.value = None`, `x.value = 0.75`, `y.value = None` after this PR, irrespective if copy or deepcopy was used, which is probably not good.

**Comment by phschiele** [comment]
An alternative would be to override `__copy__` and `__deepcopy__` to fail and point to the `.copy()` function instead.

**Comment by SteveDiamond** [comment]
> An alternative would be to override `__copy__` and `__deepcopy__` to fail and point to the `.copy()` function instead.

That sounds much better. We put a lot of work into `.copy()`. I agree that getting obj.value = None, x.value = 0.75, y.value = None above is not desirable behavior.

**Comment by adishavit** [comment]
Cc: @michael-123123 
IIRC, he had done some work on cloning variables.

**Comment by rileyjmurray** [comment]
Ping @phschiele what's the status on this?

**Comment by phschiele** [comment]
@SteveDiamond @rileyjmurray Changed to forward `__copy__` to `.copy()` and fail on `__deepcopy__`.

**Review by SteveDiamond — APPROVED** [review]

**Comment by phschiele** [comment]
@SteveDiamond are you waiting for another review, or is this PR good to merge?

**Comment by SteveDiamond** [comment]
We can merge.

**Pull request merged**
