### PR TITLE
loggamma approximation

### PR DESCRIPTION
**Pull request by SteveDiamond**
This adds the approximation of the log-gamma function from #228. I followed the naming convention from scipy.

### CODE REVIEW

**Comment by rileyjmurray** [comment]
I think it would be good to add tolerance parameters here. Like ``loggamma(x, rtol, atol)`` with relative and absolute tolerances. To keep things simple we can just use ``rtol=0.27`` and ``atol=0.04`` as defaults (since these hold for the given implementation) and raise NotImplementedError's when these values are changed.  Alternatively, the function name could be changed to ``loggamma_approx`` and we can dispense with tolerances. @akshayka what do you think?

**Comment by SteveDiamond** [comment]
For context we already have a ``log_normcdf`` which is an approximation.

**Comment by rileyjmurray** [comment]
Ah! In that case, I think this is fine. Do you want to add this atom and the other approximation to the web documentation? Or save that for a release of 1.2?

**Comment by SteveDiamond** [comment]
Maybe I'll add the docs later. I'd like to merge this in now so I don't forget.

**Pull request merged**
