### PR TITLE
Unpin setuptools

### PR DESCRIPTION
**Pull request by SteveDiamond**
## Description
Unpins setuptools so the latest version can be installed.
Issue link (if applicable): #2021

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by phschiele** [comment]
Some context: the pinning was added in #1950.
The root cause seems to be resolved: 
https://github.com/pypa/setuptools/issues/3693#issuecomment-1325363410

**Review by phschiele — APPROVED** [review]
LGTM. Perhaps we could also pin a lower version to make sure it installs on all systems, as anyone requiring more recent versions (e.g. because of vulnerabilities) would not be blocked by having a loose lower bound. I looked at the logs of the Mac/3.7 build but it did not say which version was installed, presumably it used an already installed version.

The pin was backported, so I'm adding a label to backport the unpin as well.

**Comment by SteveDiamond** [comment]
> LGTM. Perhaps we could also pin a lower version to make sure it installs on all systems, as anyone requiring more recent versions (e.g. because of vulnerabilities) would not be blocked by having a loose lower bound. I looked at the logs of the Mac/3.7 build but it did not say which version was installed, presumably it used an already installed version.

I removed the upperbound so this shouldn't be an issue right?

**Comment by phschiele** [comment]
> > LGTM. Perhaps we could also pin a lower version to make sure it installs on all systems, as anyone requiring more recent versions (e.g. because of vulnerabilities) would not be blocked by having a loose lower bound. I looked at the logs of the Mac/3.7 build but it did not say which version was installed, presumably it used an already installed version.
> 
> 
> 
> I removed the upperbound so this shouldn't be an issue right?

@SteveDiamond yes, exactly. Just saying we could also put the lower bound that also works with MacOS/3.7 for example. But fine for me as is 👍

**Pull request merged**
