### PR TITLE
Update PDLP interface for ortools 9.4

### PR DESCRIPTION
**Pull request by mlubin**
The code remains compatible with both 9.3 and 9.4. Also place conservative upper bounds on the supported version because the ortools API may change in any point release.

Closes #1868

### CODE REVIEW

**Comment by lperron** [comment]
shoud I wait for the cvxpy PR to be merged ?

**Comment by SteveDiamond** [comment]
Any idea why some of the builds failed?

**Comment by phschiele** [comment]
@mlubin The windows 3.8 build also fails in #1840. I will take a look at that one later today.

**Comment by Mizux** [comment]
> Windows failed installing scipy, no idea what that means. Could we restart that build?
> 
> @Mizux @lperron could you comment on the macos failures? [1](https://github.com/cvxpy/cvxpy/runs/7830649028?check_suite_focus=true) [2](https://github.com/cvxpy/cvxpy/runs/7830649056?check_suite_focus=true)
> 
> The errors look like:
> 
> ```
> >       from . import _pywraplp
> E       ImportError: dlopen(/usr/local/miniconda/envs/test/lib/python3.10/site-packages/ortools/linear_solver/_pywraplp.so, 2): no suitable image found.  Did find:
> E       	/usr/local/miniconda/envs/test/lib/python3.10/site-packages/ortools/linear_solver/_pywraplp.so: mach-o, but wrong architecture
> E       	/usr/local/miniconda/envs/test/lib/python3.10/site-packages/ortools/linear_solver/_pywraplp.so: mach-o, but wrong architecture
> 
> /usr/local/miniconda/envs/test/lib/python3.10/site-packages/ortools/linear_solver/pywraplp.py:13: ImportError
> ```
> 
> ```
> >           from ortools.model_builder.python import (
>                 pywrap_model_builder_helper,)
> E           ImportError: dlopen(/usr/local/miniconda/envs/test/lib/python3.9/site-packages/ortools/model_builder/python/pywrap_model_builder_helper.so, 2): no suitable image found.  Did find:
> E           	/usr/local/miniconda/envs/test/lib/python3.9/site-packages/ortools/model_builder/python/pywrap_model_builder_helper.so: mach-o, but wrong architecture
> E           	/usr/local/miniconda/envs/test/lib/python3.9/site-packages/ortools/model_builder/python/pywrap_model_builder_helper.so: stat() failed with errno=22
> ```

First:
1. On my M1 when I built the python packages they generate `macosx_11_0_universal2.whl` wheel packages (note: I've used homebrew silicon python package as runtime)
2. On my gMac (intel) i've use python installer from python.org and it has generated `macosx_10_15_x86_64.whl` wheel package.

-> I need to find a way to generate `macosx_*_arm64.whl` package on M1 thus intel mac won't try to use universal_2 (M1 only ) package...

**Comment by mlubin** [comment]
The remaining CI failures are all related to installing numpy. (It's possible they could be masking additional failures related to or-tools.)

**Comment by SteveDiamond** [comment]
Thanks for fixing this so quickly!

**Pull request merged**
