### PR TITLE
Adding dual variables for SciPy LP solver interfaces #1425

### PR DESCRIPTION
**Pull request by Michael-git96**
Adding dual variables when the SciPy solver is used with methods "highs", "highs-ds" or "highs-ipm" and the Scipy version is >= 1.7.0 . Linked to Issue #1425 .

### CODE REVIEW

**Comment by Michael-git96** [comment]
Two things I would like to note:

1) I left the parameter duals as False in the tests in cvxpy/tests/test_conic_solvers.py, since the dual variables are only returned when the user has a SciPy version >= 1.7.0 and the method is one of the HiGHS methods. 

2) I believe the HiGHS methods return the dual variables with the sign switched, so I had to switch it back in line 186 and 190 within cvxpy/reductions/solvers/conic_solvers/scipy_conif.py . I ran a simple LP and calculated the Lagrangian dual manually and it seemed like the sign was switched in the result, but I would appreciate it if someone could double check that.

**Comment by Michael-git96** [comment]
Update on the two points above:

1) I ran the SCIPY tests with dual set to True (and a SciPy version of 1.7.0) and they passed, so the duals work when they are returned.

2) I found a note in the documentation of linprog for SciPy 1.7.0 (https://docs.scipy.org/doc/scipy-1.7.0/reference/optimize.linprog-highs.html#optimize-linprog-highs) which supports the suspicion I had about the dual variables being returned with the sign switched:
> The result fields ineqlin, eqlin, lower, and upper all contain marginals, or partial derivatives of the objective function with respect to the right-hand side of each constraint. These partial derivatives are also referred to as “Lagrange multipliers”, “dual values”, and “shadow prices”. The sign convention of marginals is opposite that of Lagrange multipliers produced by many nonlinear solvers.

**Comment by rileyjmurray** [comment]
Thanks for doing this, @Michael-git96!

> Update on the two points above:
> 
> 1. I ran the SCIPY tests with dual set to True (and a SciPy version of 1.7.0) and they passed, so the duals work when they are returned.

Could you change the tests so that the check for duals is performed when the appropriate SciPy version is installed? You could look at adding a class attribute like ``SCIPY.DUALS = StrictVersion(scipy.__version__) >= StrictVersion('1.7.0')`` and then in the tests change lines like ``StandardTestLPs.test_lp_0(solver='SCIPY', duals=False)`` to ``StandardTestLPs.test_lp_0(solver='SCIPY', duals=SCIPY.DUALS)`` (you'd need to import the SCIPY solver object right after https://github.com/cvxpy/cvxpy/blob/693a58a7d784bca7c0b6460f462ec22326555f6d/cvxpy/tests/test_conic_solvers.py#L1434).

**Comment by Michael-git96** [comment]
Thanks for the suggestion @rileyjmurray, I have added in the class attribute so now the duals will be tested if a SciPy version higher than or equal to 1.7.0 is installed.

**Review by rileyjmurray — APPROVED** [review]

**Comment by rileyjmurray** [comment]
Looks good to me. Thanks again, @Michael-git96!

**Pull request merged**
