### PR TITLE
Added feature mentioned in issue #1695

### PR DESCRIPTION
**Pull request by Brown2345**
## Description
vec and flatten both gain the option order as an optional argument, allowing a change of ordering from Fortran to C, if desired.
Issue link: https://github.com/cvxpy/cvxpy/issues/1695

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
This is good! You should add tests as well, maybe in test_atoms.py.

**Review by rileyjmurray — CHANGES_REQUESTED** [review]
@Brown2345 I know this PR is simple and you opened it a while ago, but are you interested in finishing it? We'd need a couple of simple unit tests and to update the function docstrings. Let us know how you'd like to proceed.

**Comment by rileyjmurray** [comment]
ping @Brown2345

**Comment by SteveDiamond** [comment]
@rileyjmurray I added tests and doc-strings.

**Review by phschiele — COMMENTED** [review]
Thanks for adding the test cases @SteveDiamond.
They cover both orders + the default argument for constants and variables, which is the full scope of the PR.
I agree with the notion in the issue that this is not a bug, as it was not mentioned before.

**Comment by SteveDiamond** [comment]
Thanks, merging in!

**Pull request merged**
