### PR TITLE
Prep Patch/1.3.2

### PR DESCRIPTION
**Pull request by phschiele**
The following PRs have been merged since the last patch:

| Link | Type | 1.3.x | 1.2.x | 1.1.x | Comment
|--------|--------|--------|--------|--------|--------|
| #2047 | Bug | ✔ |   |   | |
| #2073 | Other |   |   |   | |
| #2078 | Doc |   |   |   | |
| #2085 | Doc |   |   |   | |
| #2080 | Bug | ✔ |   |   | |
| #2081 | Other |   |   |   | |
| #2084 | Bug | ✔ |   |   | |
| #2057 | Feat |   |   |   | |
| #2088 | Other | ✔ |   |   | |
| #2069 | Feat |   |   |   | |
| #2094 | Other|   |   |   | |
| #2103 | Feat |   |   |   | |
| #2105 | Bug (?) |   |   |   | |
| #2110 | Feat  |   |   |   | |
| #2111 | Other |   |   |   | |
| #2113 | Feat |   |   |   | |
| #2108 | Feat (?) |   |   |   | |
| #2118 | Other (?) |   |   |   | |
| #2120 | Other |   |   |   | |
| #2116 | Feat |   |   |   | |
| #2091 | Feat |   |   |   | |
| #2123 | Bug | ✔ |   |   | |
| #2117 | Feat |   |   |   | |
| #2130 | Bug |   |   |   | |
| #2131 | Bug | ✔ |   |   | |
| #2086 | Bug | ✔ |   |   | |
| #2134 | Bug | ✔ |   |   | |
| #2127 | Feat |   |   |   | |
| #2126 | Bug | ✔ |   |   | |
| #2119 | Feat |   |   |   | |
| #2141 | Feat |   |   |   | |
| #2139 | Feat  |   |   |   | |
| #2146 | Feat  |   |   |   | |
| #2147 | Feat |   |   |   | |
| #2097 | Feat |   |   |   | |
| #2125 | Feat  |   |   |   | |
| #1821 | Bug | ✔ |  |  | resolves (?) #1747
| #2160  | Bug  | ✔ |   |   | |
| #2159 | Bug  | ✔ |   |   | |
| #2161  | Bug  | ✔ |   |   | |

### CODE REVIEW

**Comment by rileyjmurray** [comment]
That's a nice collection! I love making a table like this, @phschiele.

**Comment by PTNobel** [comment]
I think #2047 should be included; it was tagged for backporting but did not get included in the 1.3.1 release at the request of 364a, since 1.3.1 came out during the final exam and that function's previous behaviour was described in a question on the final.

**Comment by phschiele** [comment]
I have included #2047 as suggested by @PTNobel, and all tests are passing now.

There are 3 PRs where we could discuss whether or not it makes sense to backport them:
- https://github.com/cvxpy/cvxpy/pull/2105
Removes reductions from the top level. This was labelled as a bug, but we might consider keeping the imports as is not to break code on the same minor version.
- https://github.com/cvxpy/cvxpy/pull/2108
This is a new feature, but we might consider including it in the 1.3 patch to enable faster adoption of Clarabel before including it in future versions as a dependency
- https://github.com/cvxpy/cvxpy/pull/2118
This removes a deprecated install method and is labelled to be backported. This could break some installations.

Feel free to hover over the PRs in the table if you spot anything else that should be considered for backporting.

**Comment by rileyjmurray** [comment]
I can’t review right now but I will have comments so please wait before
releasing

**Comment by SteveDiamond** [comment]
> I have included #2047 as suggested by @PTNobel, and all tests are passing now.
> 
> There are 3 PRs where we could discuss whether or not it makes sense to backport them:
> 
> * [fix: remove reductions import in top-level __init__.py #2105](https://github.com/cvxpy/cvxpy/pull/2105)
>   Removes reductions from the top level. This was labelled as a bug, but we might consider keeping the imports as if for backports, not to break code on the same minor version.
> * [Support SDPs for Clarabel ver >= 0.5.0 #2108](https://github.com/cvxpy/cvxpy/pull/2108)
>   This is a new feature, but we might consider including it in the 1.3 patch to enable faster adoption of Clarabel before including it in future versions as a dependency
> * [`setup.py`: Remove `setup_requires`, remove setuptools from `install_requires' #2118](https://github.com/cvxpy/cvxpy/pull/2118)
>   This removes a deprecated install method and is labelled to be backported. This could break some installations.
> 
> Feel free to hover over the PRs in the table if you spot anything else that should be considered for backporting.

I'm in favor of backporting #2108 to 1.3 and leaving the others for 1.4. But I don't feel strongly about it.

**Comment by rileyjmurray** [comment]
Here are my two cents on each of the three PRs you mentioned, @phschiele.
 
#### https://github.com/cvxpy/cvxpy/pull/2105
> Removes reductions from the top level. This was labeled as a bug, but we might consider keeping the imports as if for backports, not to break code on the same minor version.

Let's not risk breaking code unless we have to. While it's fine to call this a bug, it's not a "correctness bug" that a casual user might encounter. So I would prefer to _not_ backport this PR.

#### https://github.com/cvxpy/cvxpy/pull/2108
> This is a new feature, but we might consider including it in the 1.3 patch to enable faster adoption of Clarabel before including it in future versions as a dependency

I would not be in favor of adding this to a patch. My preference would be something like "update Clarabel's interface in 1.4, make Clarabel a dependency in 1.5, and make Clarabel high on our solver priority list in 1.6." With our current release cadence, that would take a long time, but there is no reason why we can't make releases more often. If I recall correctly,  @SteveDiamond was in favor of releasing as often as once every three months back when we adopted semantic versioning.

#### https://github.com/cvxpy/cvxpy/pull/2118
> This removes a deprecated install method and is labeled to be backported. This could break some installations.

My thoughts here are the same as for #2105; let's not risk breaking code unless there's a compelling reason to do so.

**Comment by SteveDiamond** [comment]
Please include #2160.

**Comment by phschiele** [comment]
Merging here as discussed @SteveDiamond @rileyjmurray @PTNobel.
Sonar failures are related to some duplication between (deprecated) `conv` and `convolve`.

**Pull request merged**
