### PR TITLE
Prep Patch/1.2.5

### PR DESCRIPTION
**Pull request by Paulnkk**
The following PRs have been merged since the last patch:

| Link | Type | 1.3.x | 1.2.x | 1.1.x | Comment
|--------|--------|--------|--------|--------|--------|
| #2047 | Bug | ✔ | ✔ |   | |
| #2073 | Other |   |   |   | |
| #2078 | Doc |   |   |   | |
| #2085 | Doc |   |   |   | |
| #2080 | Bug | ✔ | ✔ |   | |
| #2081 | Other |   |   |   | |
| #2084 | Bug | ✔ | ✔ |   | |
| #2057 | Feat |   |   |   | |
| #2088 | Other | ✔ | ✔ |   | |
| #2069 | Feat |   |   |   | |
| #2094 | Other|   |   |   | |
| #2103 | Feat |   |   |   | |
| #2105 | Bug (?) |   |   |   | |
| #2110 | Feat  |   |   |   | |
| #2111 | Other |   |   |   | |
| #2113 | Feat |   |   |   | |
| #2108 | Feat (?) |   |   |   | |
| #2118 | Other (?) |   |   |   | |
| #2120 | Other |   |   |   | |
| #2116 | Feat |   |   |   | |
| #2091 | Feat |   |   |   | |
| #2123 | Bug | ✔ |   |   | `tr_inv` not in 1.2 |
| #2117 | Feat |   |   |   | |
| #2130 | Bug |   |   |   | |
| #2131 | Bug | ✔ | ✔ |   | |
| #2086 | Bug | ✔ | ✔ |   | |
| #2134 | Bug | ✔ |   |   | COPT not in 1.2|
| #2127 | Feat |   |   |   | |
| #2126 | Bug | ✔ | ✔ |   | |
| #2119 | Feat |   |   |   | |
| #2141 | Feat |   |   |   | |
| #2139 | Feat  |   |   |   | |
| #2146 | Feat  |   |   |   | |
| #2147 | Feat |   |   |   | |
| #2097 | Feat |   |   |   | |
| #2125 | Feat  |   |   |   | |
| #1821 | Bug | ✔ | ✔|  | resolves (?) #1747
| #2160  | Bug  | ✔ | ✔ |   | |
| #2159 | Bug  | ✔ | ✔ |   | |
| #2161  | Bug  | ✔ |   |   | Not in 1.2 |

### CODE REVIEW

**Comment by rileyjmurray** [comment]
@Paulnkk ``PowCone3D`` is in 1.2.0, so #2131 should be added to this PR.

**Comment by Paulnkk** [comment]
> @Paulnkk `PowCone3D` is in 1.2.0, so #2131 should be added to this PR.

@rileyjmurray Thanks for the comment! I added the commit and unfortunately, I receive the following error as before (for this reason I have not included this commit):

Screenshot 2023-07-16 at 15 27 34

Additionally, I have to apologize that I made the cherry picks on `patch/1.2.5` and directly merged into `release/1.2.x` and pushed on that branch. If this is not optimal, I can create a new PR and request a merge from `patch/1.2.5` into `release/1.2.x` directly (sorry for those kind of mistakes it is my first PR of that kind but very happy to work on that!)

**Comment by rileyjmurray** [comment]
@Paulnkk I suspect there was a bug where ``PowCone3D`` was not exposed in CVXPY's top-level namespace in 1.2.x; it should have been.

**Comment by Paulnkk** [comment]
@rileyjmurray What is the best way to deal with this issue? I can make a separate commit in `patch/1.2.5` and try to solve the problem, does that work ?

**Comment by phschiele** [comment]
@Paulnkk thanks for putting this together. Let me clean up this one remaining issue here. You can get started on the 1.1 patch if you like.

**Review by phschiele — APPROVED** [review]
Looks good, thanks @Paulnkk!
I compared it against the 1.3 patch, it is identical for the fixes that we backport. 
I removed some code you added for the mosek interface which were not part of the bugfixes. Now all tests work for me locally. 

Suggestion to release as soon as the CI is fixed.

@Paulnkk Do you also have a similar PR for the 1.1.x release?

**Comment by Paulnkk** [comment]
@phschiele Yes, I am currently working on it and plan to release the PR today evening or tomorrow 👍🏻

**Comment by SteveDiamond** [comment]
Not sure why this won't run CI. Going to go ahead and merge and fix any issues later.

**Pull request merged**
