### PR TITLE
CI: Build wheels for python 3.13

### PR DESCRIPTION
**Pull request by Transurgeon**
## Description
Python 3.13 is being released October 1st, so this PR aims to add support for it in builds and CI.
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by PTNobel** [comment]
Hmmm looks like our build process doesn't support rc releases because of a conda issue. We should see if there's a conda channel with rcs and/or migrate to pipx or one of the other build systems

**Comment by Transurgeon** [comment]
> Hmmm looks like our build process doesn't support rc releases because of a conda issue. We should see if there's a conda channel with rcs and/or migrate to pipx or one of the other build systems

I found a conda channel with RC, but I am not sure how to add it to the existing build system.
See link to blog [here](https://conda-forge.org/blog/2024/09/26/python-313/).

**Comment by PTNobel** [comment]
3.13 is out now so we could try and just not worry about rcs for now

**Comment by Transurgeon** [comment]
> 3.13 is out now so we could try and just not worry about rcs for now

The CI is getting this error when trying to setup python3.13. That's why I started looking into setting up with rcs.
I'll try installing python3.13rc on my local to see if that works atleast.
```sh
  LibMambaUnsatisfiableError: Encountered problems while solving:
    - nothing provides _python_rc needed by python-3.13.0rc1-h3ec566f_100_cp313
  
  Could not solve for environment specs
  The following package could not be installed
  └─ python 3.13**  is not installable because it requires
     └─ _python_rc, which does not exist (perhaps a missing channel).
```

**Comment by Transurgeon** [comment]
ok I just tried building wheels with python3.13 on my local and it seems to work!
Will try to rerun CI to see if it works now by any chance.

**Comment by Transurgeon** [comment]
Getting an OSQP compatibility error now (conda issue seems to be fixed).
Should we open an issue on their repo at some point (this is not definitely urgent though)?
```bash
Could not solve for environment specs
The following packages are incompatible
├─ osqp is installable with the potential options
│  ├─ osqp [0.3.1|0.4.0|0.4.1|0.5.0|0.6.1] would require
│  │  └─ python >=2.7,<2.8.0a0  with the potential options
│  │     ├─ python [2.7.12|2.7.13|...|2.7.18], which can be installed;
│  │     └─ python [2.7.15|3.6.7|3.7.1] would require
│  │        └─ openssl >=1.1.1,<1.1.2.0a0 , which does not exist (perhaps a missing channel);
│  ├─ osqp [0.3.1|0.4.0] would require
│  │  └─ python >=3.5,<3.6.0a0 , which can be installed;
│  ├─ osqp [0.3.1|0.4.0|...|0.6.2] would require
│  │  └─ python >=3.6,<3.7.0a0  with the potential options
│  │     ├─ python [2.7.15|3.6.7|3.7.1], which cannot be installed (as previously explained);
│  │     └─ python [3.6.0|3.6.1|...|3.6.9], which can be installed;
│  ├─ osqp [0.4.1|0.5.0|0.6.1|0.6.2|0.6.2.post0] would require
│  │  └─ python >=3.7,<3.8.0a0  with the potential options
│  │     ├─ python [2.7.15|3.6.7|3.7.1], which cannot be installed (as previously explained);
│  │     └─ python [3.7.0|3.7.1|...|3.7.9], which can be installed;
│  ├─ osqp [0.6.1|0.6.2|...|0.6.7.post0] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ osqp [0.6.2|0.6.2.post0|0.6.3|0.6.7|0.6.7.post0] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ osqp [0.6.2.post0|0.6.3|0.6.7|0.6.7.post0] would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ osqp [0.6.3|0.6.7|0.6.7.post0] would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  └─ osqp [0.6.3|0.6.7|0.6.7.post0] would require
│     └─ python >=3.12,<3.13.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.13.* , which conflicts with any installable versions previously reported.
```

**Review by SteveDiamond — APPROVED** [review]
nice job!

**Pull request merged**
