### PR TITLE
Changing solver in tests from ECOS to CLARABEL

### PR DESCRIPTION
**Pull request by Transurgeon**
## Description
Please include a short summary of the change.
Now that we are transitioning from ECOS to CLARABEL, I think it makes sense to change all our tests to use cp.CLARABEL by default. 

P.S. Some tests are failing (mostly in ``test_DQCP``), I believe this could be due to precision or some other missing parameter? 
I am not too familiar with Clarabel, @PTNobel could you have a look please?
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by PTNobel** [comment]
Happy to, but probably not for a few days.

**Comment by PTNobel** [comment]
The DQCP bug is honestly quite concerning. We have a regression from swapping from ECOS to CLARABEL. I'll try and minimize it and explain what's wrong to send to Paul later tonight.

**Comment by PTNobel** [comment]
Just opened oxfordcontrol/Clarabel.rs#120 with an example of a problem that is broken by the differences. It seems that Clarabel is much worse about detecting primal infeasible problems and that has regressed these methods significantly.

**Comment by PTNobel** [comment]
If we want to, we could keep ECOS for DQCP and then merge this PR for now, but I think we should definitely have a longer term plan around fixing DQCP.

**Comment by SteveDiamond** [comment]
Clarabel has improved quite quickly in the past so I don't think we necessarily need to do anything besides coordinate with Paul about this. It's normal for cvxpy to expose different issues with solvers since there's so much coverage.

**Comment by Transurgeon** [comment]
@PTNobel I propose to update this PR to remove all the failing tests with DQCP.
Then we can open another PR specifically for the remaining tests as well as drop ECOS support, once the clarabel issue is resolved.

**Comment by PTNobel** [comment]
Sounds like a plan. Let's do it @Transurgeon

**Comment by Transurgeon** [comment]
@PTNobel a few tests are still failing because of precision errors (see below).
I tried looking in the clarabel [docs](https://clarabel.org/stable/api_settings/#Clarabel.Settings) but I'm still not sure what solver setting to pass to fix this issue.
image

**Comment by Transurgeon** [comment]
@PTNobel I fixed this PR by removing the precision error tests mentioned above. 
I think the failing benchmark (one of them has a "significant" change) is really weird and definitely unrelated to the changes in this PR. 
Let's move forward with this PR if you are ok with it.

**Review by PTNobel — APPROVED** [review]

**Pull request merged**
