### PR TITLE
Removes pybind11 runtime dependency

### LINKED ISSUE #2330: Unnecessary pybind11 dependency?
https://github.com/cvxpy/cvxpy/pull/2125 (released in 1.4.0) added `pybind11` as a dependency, but it seems like it is just a build dependency, not a run time dependency?

One piece of evidence is that the cvxpy conda-forge feedstock did not add pybind11 as a dependency [here](https://github.com/conda-forge/cvxpy-feedstock/pull/83) and has gotten no complaints. I noticed this because I maintain a downstream feedstock that runs `pip check` as a test and that fails for cvxpy 1.4 because pybind11 is not installed.

### PR DESCRIPTION
**Pull request by phschiele**
## Description
Removes pybind11 runtime dependency from `requirements.txt` and `pyproject.toml`.
Issue link (if applicable): resolves #2330 

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by SteveDiamond — APPROVED** [review]
LGTM

**Comment by phschiele** [comment]
@rileyjmurray The only potential downside I saw was that my IDE complains about this line now:
https://github.com/cvxpy/cvxpy/blob/0a8881d9f8ea38a54d992fd6f0cca0db41fda137/setup/extensions.py#L18

Confirmed that running `pip install -e .` works without issues.

**Comment by SteveDiamond** [comment]
There is a CI failure but it is transient. Happened to me earlier. Maybe conda is having issues?

**Comment by phschiele** [comment]
Looks like there are no objections, merging here.

**Pull request merged**
