### PR TITLE
Add __all__ variables to improve type annotations

### PR DESCRIPTION
**Pull request by r-barnes**
## Description
I'm seeing issues [similar to this one](https://github.com/microsoft/pylance-release/issues/2953) for cvxpy in vscode and it makes me sad.

I think the solution is to use an `__all__` variable as explained [here](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md).

I wasn't sure how to format the code so I ran `isort X && black X` on the files.

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [X] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [X] Add our license to new files.
- [X] Check that your code adheres to our coding style.
- [X] Write unittests.
- [X] Run the unittests and check that they’re passing.
- [X] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Thanks! @akshayka explored something similar at one point.

**Comment by phschiele** [comment]
@r-barnes Can you be a bit more specific about this issue? The linked issue mentions that an error is shown in VsCode, but I do not see such errors with CVXPY.

**Comment by SteveDiamond** [comment]
Addressed in #2246

**Comment by SteveDiamond** [comment]
Thanks for highlighting this issue!

**Pull request closed without merging**
