### PR TITLE
Patch/1.5.4

### PR DESCRIPTION
**Pull request by Transurgeon**
| Link | Type | 1.5.x | Comment |
|------|------|-------|---------|
| #2541    |   Bug   |   ✅  |         |
| #2542    |   Bug   |   ✅  |         |
|  #2549   |   Bug  |   ✅  |         |
|  #2609     |  Bug  |    ✅  |         |
|  #2624   |   Bug  |   ✅  |         |
|  #2630   |   Interface update  |   ✅  |         |

### CODE REVIEW

**Comment by Transurgeon** [comment]
it seems like the new version of gurobipy is breaking CI, i'll wait for it to get fixed before moving forward with this patch.

**Comment by Transurgeon** [comment]
@simonbowly sorry for the ping, but I remember you contributed to #2541, so I was wondering if you could look into this? Is the issue that cvxpy's interface needs to be updated, or could there have been some issue in the new gurobipy version?

**Comment by simonbowly** [comment]
@Transurgeon no worries, thanks for letting me know. `StatusConstClass` is an undocumented class that was removed from the `gurobipy` namespace in version 12.0. This should be replaced with the equivalent names under [GRB](https://docs.gurobi.com/projects/optimizer/en/current/reference/python/grb.html#GRB) or [GRB.Status](https://docs.gurobi.com/projects/optimizer/en/current/reference/python/grb.html#GRB.Status).

So in cvxpy these cases:

```python
if solver_status != gurobipy.StatusConstClass.TIME_LIMIT:
```

should be replaced with just:

```python
if solver_status != gurobipy.GRB.TIME_LIMIT
```

This is compatible with all older gurobipy releases as well.

**Comment by Transurgeon** [comment]
> @Transurgeon no worries, thanks for letting me know. `StatusConstClass` is an undocumented class that was removed from the `gurobipy` namespace in version 12.0. This should be replaced with the equivalent names under [GRB](https://docs.gurobi.com/projects/optimizer/en/current/reference/python/grb.html#GRB) or [GRB.Status](https://docs.gurobi.com/projects/optimizer/en/current/reference/python/grb.html#GRB.Status).
> 
> So in cvxpy these cases:
> 
> ```python
> if solver_status != gurobipy.StatusConstClass.TIME_LIMIT:
> ```
> 
> should be replaced with just:
> 
> ```python
> if solver_status != gurobipy.GRB.TIME_LIMIT
> ```
> 
> This is compatible with all older gurobipy releases as well.

thank you for the quick reply @simonbowly ! 
I will make a PR to update our interface now.
BTW, are you fine with being added to the list of solver interface owners? 
see here: https://github.com/cvxpy/cvxpy/discussions/2203
this is just for us to document who to reach out for solver interface related issues

**Comment by simonbowly** [comment]
> BTW, are you fine with being added to the list of solver interface owners?

Yes, that's fine by me

**Pull request merged**
