### PR TITLE
Prep for CVXPY 1.1.19 release

### PR DESCRIPTION
**Pull request by rileyjmurray**
We accumulated a number of bug fixes since CVXPY 1.1.18 that will need to go in the 1.1.19 release. We also had none of the semantic versioning infrastructure on the ``release/1.1.x`` branch. This PR adds all semantic versioning infrastructure accumulated on master (PRs #1598, #1617, #1624), as well as bugfixes for kron with parameters (issue #1656), M1 build failures (issue #1604), Anderson Acceleration docs and warning for SCS 2.X (follow-up from PR #1670).

Note that the target branch for this PR is ``release/1.1.x``. Note also that we haven't confirmed M1 build failures are actually fixed, so more changes might be needed on ``release/1.1.x`` after merging this PR if the proposed M1 fix doesn't work.

**EDIT (for anyone who might review this PR):** no need to look at changes to the source files. They're overwhelmingly copy-pasted from other PRs which were already merged. Just comment on the notes I give above (about M1) and the update I give later in this thread.

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [X] Bug fix
- [X] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [X] Add our license to new files.
- [X] Check that your code adheres to our coding style.
- [X] Write unittests.
- [X] Run the unittests and check that they’re passing.
- [X] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by rileyjmurray** [comment]
This PR should now account for essentially all bugfix-related changes accumulated on master since we moved 1.1 development to ``release/1.1.x``. The only exceptions are that I didn't propagate some documentation/example fixes or the changes related to deprecation warnings.

**Comment by SteveDiamond** [comment]
Sounds right to me, I can't think of anything you missed.

**Comment by phschiele** [comment]
@rileyjmurray Thanks for moving over the infrastructure and bug fixes!
I went through the commit history and only found this single commit that might still be added to this PR:
https://github.com/cvxpy/cvxpy/commit/744a8cb9178f8f101209350fc48887bcf3d2c804

**Comment by rileyjmurray** [comment]
Thanks for catching that, @phschiele!

**Comment by lochsh** [comment]
@rileyjmurray Would it be possible for the changes from https://github.com/cvxpy/cvxpy/pull/1677 to make it into the 1.1.19 release? Let me know if there's anything I can do to help with that. I understand if it's too late.

**Comment by rileyjmurray** [comment]
@lochsh already done, I just haven't pushed :)

**Comment by lochsh** [comment]
Amazing, thank you. Do you have a plan for when the 1.1.19 release is likely to be cut?

**Comment by rileyjmurray** [comment]
@losch either this upcoming Sunday or Monday. Your PR was merged in the nick of time!

**Comment by rileyjmurray** [comment]
I'm inclined to wait until #1648 is done before merging this PR. It would be nice to get all 1.1.19 changes in one PR.

**Comment by rileyjmurray** [comment]
Correction on commit history: https://github.com/cvxpy/cvxpy/pull/1673/commits/f35587adaf2b6aca78a85fe3c5f8d43f3d1e184c propagated the fix for PR #1684, not #1648.

**Comment by rileyjmurray** [comment]
That should do it!

**Pull request merged**
