### PR TITLE
CI: Refactoring installation of dependencies

### PR DESCRIPTION
**Pull request by Transurgeon**
## Description
Please include a short summary of the change.
This PR changes the install instructions for pyscipopt in hopes of fixing recent CI issues.
It also adds some minor changes to installing sdpa-python as well as cleaning up redundancy within the installation conditions.
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by PTNobel — APPROVED** [review]
Seems fine if CI passes

**Comment by Transurgeon** [comment]
> Seems fine if CI passes

Fails for windows 3.10/3.11 but passes on 3.12 :(
Are we ok with just removing CI tests for these cases?

I tried to look into the error but couldn't find anything specific.

**Comment by Transurgeon** [comment]
Ok, I found a related issue on the SCIP github.
https://github.com/scipopt/PySCIPOpt/issues/110.
Will look into it later today.

**Comment by Transurgeon** [comment]
Ok, CI is finally all passing again. 
I changed the CI to not test SCIP on windows (because of the original error).
I also cleaned up some conditions for sdpa-python (since the LP5 test was failing due to accuracy reasons for ubuntu)
Finally, I refactored the installation of the other dependencies.

**Pull request merged**
