### PR TITLE
Cleanup in MOSEK parameters setting

### PR DESCRIPTION
**Pull request by aszekMosek**
## Description
Tries to make Mosek parameters systematic. See https://github.com/cvxpy/cvxpy/issues/2023

Adds proper handling of the case where both parameter name and value are strings. Deprecates the use of constants from the Python API. Adapts the documentation and test accordingly.

Documentation mentions https://docs.mosek.com/latest/faq/faq.html#cvxpy  That link will be separately updated in the same style next time new Mosek docs are uploaded.

### CODE REVIEW

**Review by SteveDiamond — APPROVED** [review]
LGTM. I fixed the flake8 and isort issues.

**Comment by SteveDiamond** [comment]
@phschiele @rileyjmurray does this change look good to you? We need two approvers per our policy.

**Review by phschiele — APPROVED** [review]
LGTM, two minor remarks:
- is it intentional to raise both a deprecation and a user warning?
- one test case still uses the deprecated parameter. We could capture the warning using `with pytest.warns()` to ensure it is raised correctly.

**Comment by aszekMosek** [comment]
@phschiele Regarging the warning I followed the only existing case in https://github.com/cvxpy/cvxpy/blob/master/cvxpy/expressions/expression.py#L612 I can do it in a different way

**Comment by SteveDiamond** [comment]
> @phschiele Regarging the warning I followed the only existing case in https://github.com/cvxpy/cvxpy/blob/master/cvxpy/expressions/expression.py#L612 I can do it in a different way

Sounds good. I added ``with pytest.warns()`` to the mosek test. I'll merge after the CI passes.

**Pull request merged**
