### PR TITLE
Fix bugs in gradient computation

### PR DESCRIPTION
**Pull request by xinyueshen**
## Description
Fix bugs in gradient computation.
Issue link (if applicable): https://github.com/cvxgrp/dccp/issues/75

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [X] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [X] Check that your code adheres to our coding style.
- [x] Write unittests.
- [X] Run the unittests and check that they’re passing.
- [X] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Thanks @xinyueshen ! If it's not too much trouble, could you add some kind of test to `test_grad.py` based on the DCCP issue.

**Comment by xinyueshen** [comment]
Sure! Two test cases are added into `test_grad.py`.

**Comment by SteveDiamond** [comment]
Thanks for adding the tests. You have some flake8 (i.e., code style) issues. Please see these instructions:
https://www.cvxpy.org/contributing/index.html#code-style

**Comment by xinyueshen** [comment]
Sorry about it! The issues are fixed now.

**Review by SteveDiamond — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
