### PR TITLE
Patch 1.5.2

### PR DESCRIPTION
**Pull request by Transurgeon**
| Link | Type | 1.5.x | Comment |
|------|------|-------|---------|
| #2475    |   Build   |   ✅  |         |
| #2461    |   Bug   |   ✅  |         |
|  #2454   |   Clarification  |   ✅  |         |
|  #2452    |  Doc  |    ✅  |         |
|  #2392    |  Build  |    ✅  |         |

### CODE REVIEW

**Comment by Transurgeon** [comment]
I think we should also add #2392 to fix all the build errors.

**Comment by phschiele** [comment]
Thanks @Transurgeon! It would be best to also back port the updates to the CI to make sure the release goes smoothly.

**Comment by Transurgeon** [comment]
> Thanks @Transurgeon! It would be best to also back port the updates to the CI to make sure the release goes smoothly.

Could you clarify what you mean by CI updates? Does that include all the bumps that the bot is doing?
Thanks!

**Comment by phschiele** [comment]
@Transurgeon yes, exactly. All the merged PRs opened by Dependabot. It's not guaranteed that we would need those minor updates, but we observed in the past that outdated CI versions caused issues during deployment.

**Comment by PTNobel** [comment]
@phschiele Done.

**Review by phschiele — APPROVED** [review]

**Pull request merged**
