### PR TITLE
Map imprecise status of COPT to optimal_inaccurate of CVXPY

### PR DESCRIPTION
**Pull request by wujianjack**
## Description
Please include a short summary of the change.
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Review by SteveDiamond — APPROVED** [review]
LGTM

**Comment by rileyjmurray** [comment]
@SteveDiamond this was merged into the ``release/1.3.x`` branch, not ``master``. Was that intended?

**Comment by SteveDiamond** [comment]
> @SteveDiamond this was merged into the `release/1.3.x` branch, not `master`. Was that intended?

No that was  not intended.

@wujianjack please only make PRs into master. I will revert this.

**Comment by wujianjack** [comment]
> > @SteveDiamond this was merged into the `release/1.3.x` branch, not `master`. Was that intended?
> 
> No that was not intended.
> 
> @wujianjack please only make PRs into master. I will revert this.

Ah, okay. I thought this is minor fix and maybe better merged into 1.3.x release branch. I will open a new PR to master, thanks for the information.

**Pull request merged**
