### PR TITLE
Patch 1.5.3

### PR DESCRIPTION
**Pull request by Transurgeon**
| Link | Type | 1.5.x | Comment |
|------|------|-------|---------|
| #2484    |   Bug   |   ✅  |         |
| #2494    |   Bug   |   ✅  |         |
|  #2509   |   Bug  |   ✅  |         |
|  #2508     |  Bug  |    ✅  |         |
|  #2496   |   Dropping Dependency  |   ✅  |         |
|  #2524     |  Interface Bug |    ✅  |         |

### CODE REVIEW

**Comment by Transurgeon** [comment]
to fix the CI build failures we might need to introduce the following PRs:
- https://github.com/cvxpy/cvxpy/pull/2496
- https://github.com/cvxpy/cvxpy/pull/2524
-

**Comment by Transurgeon** [comment]
Ok this looks ready to me. 
The PR benchmarks are failing because the code in this branch (prior to this PR) is triggering the error that is resolved in #2494 .
See the current commit here https://github.com/cvxpy/cvxpy/commit/f4766bcc for reference.
Also a screenshot of the benchmarks logs is attached below (all benchmarks are running for this commit :) ). 
image

**Review by SteveDiamond — APPROVED** [review]
LGTM!

**Comment by PTNobel** [comment]
I don't think changing the install requirements on a patch release is appropriate if we can avoid it.

**Review by PTNobel — APPROVED** [review]
Looks good! I'll release.

**Pull request merged**
