### PR TITLE
More types

### PR DESCRIPTION
**Pull request by r-barnes**

### CODE REVIEW

**Comment by r-barnes** [comment]
I'll circle back to this; I've created a circular dependency that's causing an import error.

**Comment by phschiele** [comment]
Hi @r-barnes, would you mind changing
```python
def __init__(self, shape: Tuple[int] ...
```
to 
```python
def __init__(self, shape: Union[int,Tuple[int]] ...
```
in [leaf.py](https://github.com/cvxpy/cvxpy/blob/273caef73d75f1246bff54a1aaea601da4687258/cvxpy/expressions/leaf.py#L87)?

**Comment by r-barnes** [comment]
@phschiele : I've made that change. Working on getting tests to pass now.

**Comment by SteveDiamond** [comment]
Can we try to get this merged? I fixed the merge conflicts but probably still needs work.

**Comment by phschiele** [comment]
@SteveDiamond @r-barnes I have also created a [PR](https://github.com/r-barnes/cvxpy/pull/2) in @r-barnes' fork to fix the circular imports.

So either @r-barnes can merge the PRs, or the commits can be cherry-picked into this PR by the maintainers, whatever is easier.

**Comment by SteveDiamond** [comment]
@phschiele I cherry picked your changes.

**Comment by phschiele** [comment]
@SteveDiamond I have pushed another commit (547ea08) that should fix the test failures for Python 3.6.

**Review by SteveDiamond — APPROVED** [review]
LGTM

**Pull request merged**
