### PR TITLE
Implements inplace mutation error

### PR DESCRIPTION
**Pull request by PTNobel**
## Description

Implementing @rileyjmurray's suggestion from #2282 that we should error when someone attempts inplace mutation of a CVXPY expression.

This is a breaking change for the following code:

```python
x = cp.Variable()
x += 1
``` 

It also improves the error message on code we broke a few releases ago:

```python
x = cp.Variable(4)
c = np.array([1, 2, 3, 4])
x += c
```

It is possible to not break the first code while improving the error messages on the other code.

Once we have consensus on what we want this to do, I'll write unit tests.

## Type of change
- [ ] New feature (backwards compatible)
- [x] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
I would prefer that we break as little code as possible. It's definitely a good catch that inplace isn't playing well with NumPy, but I don't think we need to ban ``x += 1`` if we can make it work.

**Comment by phschiele** [comment]
From looking at the linked issue, it seems that two cases are being mixed. Intuitively, I would expect the following:
```py
x = cp.Variable(4)
c = np.array([1, 2, 3, 4])

c += x  # fails, for the reason described by Riley
x += c  # results in x = x + c
```
This appears to be the current behavior. Roughly speaking, my expectation is that the in-place assignment works if the lhs can represent the rhs of the operator. A cvxpy expression can represent a constant array, but a numpy array can't represent a CVXPY variable.

**Comment by PTNobel** [comment]
Alright, i need to email the NumPy mailing list, since they think we are having an XY problem. I'll try and do so this weekend?

**Comment by PTNobel** [comment]
@phschiele @SteveDiamond can one of you help me figure out what is going on with pytest? I'm very confused.

**Comment by phschiele** [comment]
> @phschiele @SteveDiamond can one of you help me figure out what is going on with pytest? I'm very confused.

Should be

```py
match=re.escape(__INPLACE_MUTATION_ERROR__)
```

because of special characters.

**Comment by PTNobel** [comment]
Okay, I think that this is ready to merge @phschiele @SteveDiamond

**Review by phschiele — APPROVED** [review]
Thanks for this @PTNobel, let's merge once the final CI run passes.

**Pull request merged**
